### ISSUE TITLE
Cookie church config

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/StreamingLiveApp#20]
The 1 second loading screen isn't ideal.  Let's try to eliminate it.  When we look up the host id based on subdomain, store that value in a cookie so that the lookup will not need to be repeated next time.

Also cookie the colors used by the church's theme.  We will still need to re-request those, but it could allow the page to render in the mean time.  I think the base64 logo would be too large to store in a cookie, that won't be able to show up instantly.

**Comment by pranavmalvawala** [comment]
Resolved
