### ISSUE TITLE
Make Service Times Less Ambiguous

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/StreamingLiveApp#58]
These times are hard to understand.  What they mean is.

- The displayed service time will show as 9am.
- The page will switch to the video 8 minutes early at 8:52am (to display a welcome countdown usually)
- At 8:45am, the chat will become unlocked where people can talk.
- At 10:22am the video will go away (90 min after 8:52am)

![image](https://user-images.githubusercontent.com/1447203/169717962-2f8a56c6-d9e5-4c15-80d5-e25852bddd89.png)

Find a way to make this more intuitive.  Maybe just show the calculated times above each field?  "Total Service Duration (8:52am-10:22am), "Enable Chat an prayer: 8:45am-10:22pm)".  Perhaps a more significant reworking of the fields like time pickers instead.

**Comment by PhotoPaul** [comment]
https://github.com/LiveChurchSolutions/StreamingLiveApp/commit/616a47371e6bef352f0142e0181d9da324428625 & https://github.com/LiveChurchSolutions/AppBase/commit/a120255d02445a5e646e002572fa02b8df7c2854

**Comment by jzongker** [comment]
Love it!
