### ISSUE TITLE
Enforce Correct Video Url Format

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/StreamingLiveApp#59]
This field also frequently confuses people.  We are looking for just the ID of the youtube video as shown, but it's hard for people to understand.  They'll typically enter the url in a number of different formats:

- https://www.youtube.com/watch?v=XulWro5xxjw
- https://youtu.be/XulWro5xxjw
- https://www.youtube.com/embed/XulWro5xxjw

See if we can find a way to strip it down to just the ID regardless of what format they enter.  I think a regex for exactly 11 sequential alphanumeric characters will do it for youtube?  We should do the same for FB and Vimeo urls if possible.

![image](https://user-images.githubusercontent.com/1447203/169718328-1fbc2036-eebe-4670-a70c-1af37345500b.png)

**Comment by PhotoPaul** [comment]
@jzongker You can achieve this with the following:
```typescript
let yid = val.match(/.*(?:youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=)([^#\&\?]*).*/);
if(yid != null && yid.length > 1) {
  console.log(yid[1]);
}
```

Before I mess with it though, can you please confirm that you are looking to replace the method `getYouTubeKey()` that's already being used? Do you have specific cases that are failing and that we should test?
https://github.com/LiveChurchSolutions/StreamingLiveApp/blob/6a7578f54ecf26df9d5e3113b954d88fcf43c51f/src/admin/settings/components/ServiceEdit.tsx#L60-L70

**Comment by jzongker** [comment]
I'm sorry, let's close this one.  I had forgotten this had already been fixed.  I'm not aware of any formats not currently working.  I don't think the alternative code example will work.  It appears to only handle "youtu.be" urls not "youtube.com".

**Comment by PhotoPaul** [comment]
@jzongker
This regex match actually works for both youtube.com and youtu.be links: https://jsfiddle.net/uLejonf4/1/
