### ISSUE TITLE
Customize Appearance in Streaming Live is not working

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/StreamingLiveApp#63]
https://user-images.githubusercontent.com/65249159/193015354-5d63c378-940e-45b4-a923-1973a16ce0f2.mp4

I got this from someone trying to make a tutorial for us 

But when I tried on my account I click on customizeappearance  and it sends me in a loop going to churchapps.org

https://user-images.githubusercontent.com/65249159/193015986-573aa69b-4ac9-4f03-a927-e9bb9eca8ebe.mp4

**Comment by pranavmalvawala** [comment]
Actually what's happening for you is correct behavior. The color panel you see on the right is supposed to change how your church looks and you did click on customize appearance setting. So the behavior is correct. 

I'm tracking down what's the issue for that user.

**Comment by PhotoPaul** [comment]
@pranavmalvawala
Shouldn't the church get automatically picked? If I tracked it down correctly, the decoded.churchId should be already set by the time execution gets at LoginPage.tsx:91

**Comment by pranavmalvawala** [comment]
True! it should be. It used to work like that. Right now what I think here is, the user doesn't have permissions to admin section of the church that's why the page goes blank for me. 

We better redirect or even better hide the link itself from streamingLive. What do you think?

**Comment by pranavmalvawala** [comment]
Okay so I'm digging through the code and finding the solution but yes I saw that those links only show up only when you have permissions so that's nice

**Comment by pranavmalvawala** [comment]
I think its fixed. Can you try and lemme know @mbyrdLCS

**Comment by mbyrdLCS** [comment]
As far as I can tell it is working still waiting on Jeremiah who is making the tutorial
